### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by msureshmewara** [yohhoy/heifreader#2]
[ImageReader-1440x960f4m1-31732-3] Failed to release buffer: Unknown error -1 (1)
10-26 07:41:38.943 31732-2027/jp.yohhoy.heifreader E/ImageReader_JNI: Producer output buffer format: 0x7fa30c06, ImageReader configured format: 0x4
10-26 07:41:38.958 31732-2027/jp.yohhoy.heifreader E/HeifReader: rendering RGB565 format failure
                                                                 jp.yohhoy.heifreader.HeifReader$FormatFallbackException: java.lang.UnsupportedOperationException: The producer output buffer format 0x7fa30c06 doesn't match the ImageReader's configured buffer format 0x4.
                                                                     at jp.yohhoy.heifreader.HeifReader.renderHevcImageWithFormat(HeifReader.java:394)
                                                                     at jp.yohhoy.heifreader.HeifReader.decodeByteArray(HeifReader.java:149)
                                                                     at jp.yohhoy.heifreader.HeifReader.decodeFile(HeifReader.java:180)
                                                                     at jp.yohhoy.heifreader.HeifReader.decodeStream(HeifReader.java:243)
                                                                     at jp.yohhoy.heifreader.MainActivity$1$1.doInBackground(MainActivity.java:76)
                                                                     at jp.yohhoy.heifreader.MainActivity$1$1.doInBackground(MainActivity.java:72)
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                     at java.lang.Thread.run(Thread.java:764)
                                                                  Caused by: java.lang.UnsupportedOperationException: The producer output buffer format 0x7fa30c06 doesn't match the ImageReader's configured buffer format 0x4.
                                                                     at android.media.ImageReader.nativeImageSetup(Native Method)
                                                                     at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:439)
                                                                     at android.media.ImageReader.acquireNextImage(ImageReader.java:493)
                                                                     at jp.yohhoy.heifreader.HeifReader.renderHevcImageWithFormat(HeifReader.java:392)
                                                                     at jp.yohhoy.heifreader.HeifReader.decodeByteArray(HeifReader.java:149) 
                                                                     at jp.yohhoy.heifreader.HeifReader.decodeFile(HeifReader.java:180) 
                                                                     at jp.yohhoy.heifreader.HeifReader.decodeStream(HeifReader.java:243) 
                                                                     at jp.yohhoy.heifreader.MainActivity$1$1.doInBackground(MainActivity.java:76) 
                                                                     at jp.yohhoy.heifreader.MainActivity$1$1.doInBackground(MainActivity.java:72) 
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                     at java.lang.Thread.run(Thread.java:764)

**Comment by yohhoy** [comment]
Thanks for your reporting. It seems that above log is same to [comment on #1](https://github.com/yohhoy/heifreader/issues/1#issuecomment-339568022), close this issue.
