### ISSUE TITLE
Bad Position Issue

### ISSUE THREAD

**Issue by renovatio0424** [yohhoy/heifreader#4]
i test at Galaxy 6 ( Android 7.0 )
i import the project from your git
i experience this issue

```
04-09 18:16:51.782 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@9d02e27[MainActivity]: ViewPostImeInputStage processPointer 0
04-09 18:16:51.786 24531-24531/jp.yohhoy.heifreader W/System: ClassLoader referenced unknown path: /system/framework/QPerformance.jar
04-09 18:16:51.786 24531-24531/jp.yohhoy.heifreader E/BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
04-09 18:16:51.786 24531-24531/jp.yohhoy.heifreader V/BoostFramework: BoostFramework() : mPerf = null
04-09 18:16:51.884 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@9d02e27[MainActivity]: ViewPostImeInputStage processPointer 1
04-09 18:16:51.884 24531-24531/jp.yohhoy.heifreader D/AbsListView: onTouchUp() mTouchMode : 0
04-09 18:16:52.045 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: ThreadedRenderer.create() translucent=true
04-09 18:16:52.049 24531-24531/jp.yohhoy.heifreader D/InputTransport: Input channel constructed: fd=105
04-09 18:16:52.049 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: setView = DecorView@2e99e21[heic] touchMode=true
04-09 18:16:52.052 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: dispatchAttachedToWindow
04-09 18:16:52.060 24531-24612/jp.yohhoy.heifreader D/NetworkSecurityConfig: No Network Security Config specified, using platform default
04-09 18:16:52.070 24531-24612/jp.yohhoy.heifreader I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-09 18:16:52.070 24531-24612/jp.yohhoy.heifreader I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-09 18:16:52.079 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[92,994][1347,1661] result=0x27 surface={isValid=true 490550738432} surfaceGenerationChanged=true
04-09 18:16:52.079 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: mHardwareRenderer.initialize() mSurface={isValid=true 490550738432} hwInitialized=true
04-09 18:16:52.080 24531-24562/jp.yohhoy.heifreader D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1255x667]-format:1
04-09 18:16:52.083 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: MSG_WINDOW_FOCUS_CHANGED 1
04-09 18:16:52.083 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 490550738432}
04-09 18:16:52.099 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
04-09 18:16:52.107 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@9d02e27[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
04-09 18:16:52.995 24531-24612/jp.yohhoy.heifreader I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-09 18:16:52.996 24531-24612/jp.yohhoy.heifreader I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-09 18:16:53.755 24531-24612/jp.yohhoy.heifreader I/HeifReader: HEIC caching elapsed=126.06175[msec]
04-09 18:16:53.793 24531-24612/jp.yohhoy.heifreader W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
04-09 18:16:53.793 24531-24612/jp.yohhoy.heifreader W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
04-09 18:16:53.793 24531-24612/jp.yohhoy.heifreader W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
04-09 18:16:53.935 24531-24612/jp.yohhoy.heifreader D/HeifReader: HEIC ftyp=FileTypeBox[majorBrand=mif1;minorVersion=0;compatibleBrand=mif1;compatibleBrand=heic]
04-09 18:16:53.936 24531-24612/jp.yohhoy.heifreader D/HeifReader: HEIC primary item_ID=1002
04-09 18:16:53.936 24531-24612/jp.yohhoy.heifreader I/HeifReader: HEIC image size=1440x960
04-09 18:16:53.936 24531-24612/jp.yohhoy.heifreader D/HeifReader: HEIC HEVC profile=1 level=6.2 bitDepth=8
04-09 18:16:53.938 24531-24612/jp.yohhoy.heifreader D/HeifReader: HEIC bitstream offset=534 length=131974
04-09 18:16:53.952 24531-24612/jp.yohhoy.heifreader E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                      Process: jp.yohhoy.heifreader, PID: 24531
                                                                      java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                          at java.lang.Thread.run(Thread.java:762)
                                                                       Caused by: java.lang.IllegalArgumentException: Bad position 134381/131974
                                                                          at java.nio.Buffer.position(Buffer.java:249)
                                                                          **at jp.yohhoy.heifreader.HeifReader.extractBitstream(HeifReader.java:352)
                                                                          at jp.yohhoy.heifreader.HeifReader.decodeByteArray(HeifReader.java:142)
                                                                          at jp.yohhoy.heifreader.HeifReader.decodeFile(HeifReader.java:180)
                                                                          at jp.yohhoy.heifreader.HeifReader.decodeStream(HeifReader.java:243)
                                                                          at jp.yohhoy.heifreader.MainActivity$1$1.doInBackground(MainActivity.java:71)
                                                                          at jp.yohhoy.heifreader.MainActivity$1$1.doInBackground(MainActivity.java:67)**
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                          at java.lang.Thread.run(Thread.java:762) 
04-09 18:16:54.067 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: MSG_WINDOW_FOCUS_CHANGED 0
04-09 18:16:54.321 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@9d02e27[MainActivity]: mHardwareRenderer.destroy()#1
04-09 18:16:54.355 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@9d02e27[MainActivity]: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
04-09 18:16:54.374 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: mHardwareRenderer.destroy()#1
04-09 18:16:54.396 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: Relayout returned: oldFrame=[92,994][1347,1661] newFrame=[92,994][1347,1661] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
04-09 18:16:54.718 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@9d02e27[MainActivity]: mHardwareRenderer.destroy()#4
04-09 18:16:54.719 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@9d02e27[MainActivity]: dispatchDetachedFromWindow
04-09 18:16:54.743 24531-24531/jp.yohhoy.heifreader D/InputTransport: Input channel destroyed: fd=87
04-09 18:16:54.755 24531-24531/jp.yohhoy.heifreader E/WindowManager: android.view.WindowLeaked: Activity jp.yohhoy.heifreader.MainActivity has leaked window DecorView@2e99e21[heic] that was originally added here
                                                                         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:572)
                                                                         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:97)
                                                                         at android.app.Dialog.show(Dialog.java:419)
                                                                         at android.app.ProgressDialog.show(ProgressDialog.java:151)
                                                                         at android.app.ProgressDialog.show(ProgressDialog.java:139)
                                                                         **at jp.yohhoy.heifreader.MainActivity$1.onItemClick(MainActivity.java:66)**
                                                                         at android.widget.AdapterView.performItemClick(AdapterView.java:339)
                                                                         at android.widget.AbsListView.performItemClick(AbsListView.java:1705)
                                                                         at android.widget.AbsListView$PerformClick.run(AbsListView.java:4171)
                                                                         at android.widget.AbsListView$13.run(AbsListView.java:6735)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
04-09 18:16:54.755 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: mHardwareRenderer.destroy()#4
04-09 18:16:54.757 24531-24531/jp.yohhoy.heifreader D/ViewRootImpl@aa45488[heic]: dispatchDetachedFromWindow
04-09 18:16:54.782 24531-24531/jp.yohhoy.heifreader D/InputTransport: Input channel destroyed: fd=105
```

**Comment by yohhoy** [comment]
Which HEIC file (content name) did you select?

**Comment by renovatio0424** [comment]
every images

**Comment by shaggyarora94** [comment]
Having the same issue.

**Comment by dustinshu** [comment]
same issue with me

**Comment by RJSDevel** [comment]
same issue with me

**Comment by RJSDevel** [comment]
All images

**Comment by 10045125** [comment]
I also encountered such a problem, how can I solve it?

**Comment by yohhoy** [comment]
The cause of this error is https://github.com/nokiatech/heif/commit/b05c0aed788dc90b91877ec82df68ee9d48b0fd6, they says "Update HEIF files, regenerated with the new writer." If we use old HEIF files, it works.

```patch
- private static final String URL_BASE = "https://github.com/nokiatech/heif/raw/gh-pages/content/images/";
+ private static final String URL_BASE = "https://github.com/nokiatech/heif/raw/ce04febfbf6f9aba9df635d6bcfbf3f447f9af2c/content/images/";
````

**Comment by yohhoy** [comment]
The value of `ItemLocationBox.items[0].extents[0].extentOffset` is changed between previous and current HEIC files.

Previous autumn_1440x960.heic:
```
ItemLocationBox{offsetSize=4, lengthSize=4, baseOffsetSize=4, indexSize=0, items=[
  Item{baseOffset=548, itemId=20002, constructionMethod=0, dataReferenceIndex=0,
    extents=[Extent{extentOffset=0, extentLength=289408, extentIndex=0}]},
  Item{baseOffset=289964, itemId=20003, constructionMethod=0, dataReferenceIndex=0,
    extents=[Extent{extentOffset=0, extentLength=3658, extentIndex=0}]}]}
```
Current autumn_1440x960.heic:
```
ItemLocationBox{offsetSize=4, lengthSize=4, baseOffsetSize=4, indexSize=0, items=[
  Item{baseOffset=534, itemId=1002, constructionMethod=0, dataReferenceIndex=0,
    extents=[Extent{extentOffset=8, extentLength=289408, extentIndex=0}]},
  Item{baseOffset=534, itemId=1005, constructionMethod=0, dataReferenceIndex=0,
    extents=[Extent{extentOffset=289416, extentLength=3658, extentIndex=0}]}]}
```
