### ISSUE TITLE
Compile failed on macOS Catalina 10.15 using Android Studio 3.5.3

### ISSUE THREAD

**Issue by zty5678** [yohhoy/heifreader#7]
org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/Users/xxxxxxx/Library/Android/sdk/build-tools/28.0.3/i686-linux-android-ld''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:232)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:356)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:38)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/Users/xxxxxxx/Library/Android/sdk/build-tools/28.0.3/i686-linux-android-ld'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:97)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:70)
	... 7 more
Caused by: java.io.IOException: Cannot run program "/Users/xxxxxxx/Library/Android/sdk/build-tools/28.0.3/i686-linux-android-ld" (in directory "/Users/xxxxxxx/Downloads/gitrepo4/heifreader-master 2/app"): error=86, Bad CPU type in executable
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 10 more
Caused by: java.io.IOException: error=86, Bad CPU type in executable
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 11 more

**Comment by yohhoy** [comment]
Related? https://stackoverflow.com/questions/56553879/android-studio-cause-error-86-bad-cpu-type-in-executable

**Comment by zty5678** [comment]
> Related? https://stackoverflow.com/questions/56553879/android-studio-cause-error-86-bad-cpu-type-in-executable

Thanks for reply.   

Changing to `classpath 'com.android.tools.build:gradle:3.5.3'`, the same error. 
Changing to  `compileSdkVersion 29   buildToolsVersion "29.0.0"` also the same error.

**Comment by zty5678** [comment]
I find this:  [Renderscript not compiling after updating to macOS Catalina](https://issuetracker.google.com/issues/142590626) .  It seems like it's an android build tool bug for not compatible with macOS Catalina

**Comment by yohhoy** [comment]
Quote from https://issuetracker.google.com/issues/142590626#comment48
> Marked as fixed.
>
> The fixes have been published.
> You must update your gradle plugin version to 3.6.0-rc02 or 4.0.0-beta1, and your build tools version to 29.0.3.
> I'm closing this bug, but feel free to re-open it or submit a new one if you have additional problems.

**Comment by yohhoy** [comment]
Compile succeeded on macOS Catalina 10.15.3, AndroidStudio 3.6 at 882f8b89eae063a6ef80a1e4c283e9cc6bbde35e
