### ISSUE TITLE
unsupported FileTypeBox('ftyp') brands

### ISSUE THREAD

**Issue by mvysny** [yohhoy/heifreader#8]
Hi, thank you so much for the library. Unfortunately a very simple example file can not be loaded for the following reason:

```
    java.io.IOException: unsupported FileTypeBox('ftyp') brands
        at jp.yohhoy.heifreader.HeifReader.parseHeif(HeifReader.java:262)
        at jp.yohhoy.heifreader.HeifReader.decodeByteArray(HeifReader.java:143)
        at jp.yohhoy.heifreader.HeifReader.decodeFile(HeifReader.java:182)
```

Even though the ftyp is
```
D/HeifReader: HEIC ftyp=FileTypeBox[majorBrand=heic;minorVersion=0;compatibleBrand=mif1;compatibleBrand=heic]
```

**Comment by mvysny** [comment]
The image in question:
[hu.heic.zip](https://github.com/yohhoy/heifreader/files/4286312/hu.heic.zip)

**Comment by mvysny** [comment]
Also lossy image produced by Krita fails to load
[hu.heic.zip](https://github.com/yohhoy/heifreader/files/4288749/hu.heic.zip)

**Comment by yohhoy** [comment]
accept majorBrand='heic' image file at 4de7ec93da337c899bc7fb171a14d618f708b806.

**Comment by mvysny** [comment]
Thank you, awesome :+1:  However I tried to comment that check myself, in order to force the heifreader to read the "hu.heic" image (attached above), but the image came out corrupted (weirdly skewed). I wonder if this will require some modifications to the decoder algorithm as well...
